Fix OpenSSL import in test config
Currently the 'Create br-prov network' task fails with the following
when importing pyopenssl:

AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

This patch changes the implementation to ensure that the shade module
is installed in a specific venv used for the task execution. A variable
is not used for the common path of the venv, because Ansible at this
version does not support the use of jinja in the ansible_python_interpreter
argument.

Change-Id: I2a0bb804f50fc1c998a85f9f77c5bc3d6954a444